# Interview Scheduler Configuration
# ================================

# Basic scheduling parameters
num_candidates: 3

# Day configuration
start_time: "08:30"      # When the interview day starts
end_time: "17:00"        # When the interview day ends
slot_duration_minutes: 15  # Duration of each time slot
max_gap_minutes: 15      # Maximum allowed gap between consecutive sessions

# Panel definitions with durations
# Supported formats: '15min', '1h', '1h30min', or just numbers (minutes)
panels:
  Director: "15min"      # 15 minutes
  Competencies: "1h"     # 60 minutes
  Customers: "1h"        # 60 minutes
  HR: "45min"           # 45 minutes
  Lunch: "1h"           # 60 minutes
  Team: "45min"         # 45 minutes
  Goodbye: "30min"      # 30 minutes

# Preferred order of panels (soft constraint)
# The algorithm will try to follow this order but may deviate if necessary
order:
  - Director
  - Competencies
  - Customers
  - Lunch
  - Team
  - HR
  - Goodbye

# Availability windows for each panel
# Format: "HH:MM-HH:MM" or list of time ranges
availabilities:
  Director: "08:30-10:00"                    # Only available morning

  Competencies:                              # Multiple windows
    - "08:30-11:00"                         # Morning slot
    - "12:00-14:00"                         # Early afternoon
    - "16:00-17:00"                         # Late afternoon

  Customers: "08:30-14:00"                   # Must finish by 2 PM

  HR: "08:30-17:00"                         # Available all day

  Team: "08:30-17:00"                       # Available all day

  Goodbye: "08:30-17:00"                    # Available all day

  Lunch: "11:45-13:30"                      # Canteen serving window

# Position constraints (hard constraints)
# Force specific panels to be at specific positions in the schedule
position_constraints:
  # Director: "first"                       # Force Director to be first
  # Competencies: 1
  Goodbye: "last"                         # Goodbye must always be the last panel
  # Lunch: 3                              # Uncomment to force Lunch to be 4th panel (0-indexed)

# Panel conflicts (hard constraints)
# Panels that cannot run simultaneously due to shared resources/people
panel_conflicts:
  - ["Team", "Goodbye"]                   # Team and Goodbye share people, cannot run at same time
  # - ["Director", "HR"]                  # Uncomment if Director and HR share people
  # - ["Panel1", "Panel2", "Panel3"]     # Example: 3+ panels sharing resources